### ISSUE TITLE
Create Presentation Overview

### ISSUE THREAD

**Issue by AlexOBarnes** [AlexOBarnes/StarWatch#129]
As a project manager, I want to create a presentation for the project that clearly outlines the problem, solution, architecture, and results, so I can effectively communicate the project's value to stakeholders and demonstrate the progress made by the team.

- Create a plan for the presentation
- Get feedback before progressing to next presentation step

**Comment by AlexOBarnes** [comment]
The presentation overview has been created and is available [here](https://drive.google.com/drive/folders/0AOI8cSuHRCotUk9PVA)

**Comment by olliejth** [comment]
Outrageous demotion, will be having words.
