### ISSUE TITLE
Small int out of range error for quadhourly weather pipeline (sometimes reproducible).

### ISSUE THREAD

**Issue by MurasatoNaoya** [AlexOBarnes/StarWatch#184]
When testing the weather pipeline via its associated Lambda function, there are times when the Lambda fails to complete as it runs into a value exceeding the small int schema threshold for a column. 

It's not clear exactly where this small int error is occurring / what column it relates to, as the Lambda logs are very limited when it comes to the inner working of the ETL script itself. This issue relates to the finding of what column may be causing this error, and changing its cap to that of _int_ rather than small int.

**Comment by AlexOBarnes** [comment]
#173 #178
