### ISSUE TITLE
Add drop down location table for subscribers page

### ISSUE THREAD

**Issue by AlexOBarnes** [AlexOBarnes/StarWatch#230]
As a new user, I want to select my location from a dropdown menu during the signup process, so that I can easily personalise my astronomy and weather experience based on my geographic location.

- Add a drop down menu of locations in the subscribe page of the dashboard

**Comment by MurasatoNaoya** [comment]
An important point being that without mapping subscribers to their county, we can't make tailored recommendations to when on local celestial bodies and/or events that may be visible to them.
