### ISSUE TITLE
Create architecture diagram

### ISSUE THREAD

**Issue by AlexOBarnes** [AlexOBarnes/StarWatch#4]
As a solution architect, I want to create an architecture diagram, so that I can provide a clear and concise visual representation of the system's components, services, and interactions, in order to communicate the design and structure of the system to stakeholders and team members.

- AWS based services
- Quadhoral Pipeline
- Weekly Pipeline
- RDS database
- ECS run Dashboard

**Comment by MurasatoNaoya** [comment]
Will now delete the branch made for this change.
