### ISSUE TITLE
Update cloud architecture

### ISSUE THREAD

**Issue by AlexOBarnes** [AlexOBarnes/StarWatch#80]
As a solution architect, I want to create an architecture diagram, so that I can provide a clear and concise visual representation of the system's components, services, and interactions, in order to communicate the design and structure of the system to stakeholders and team members.

- Modify for new requirements

**Comment by MurasatoNaoya** [comment]
The specific new requirement(s) being 

1. Adding an hourly EventBridge (for potential SNS triggers and AuroraWatch API  calls)
2. Adding AuroraWatch API calls to the hourly EventBridge segment of the diagram.

**Comment by AlexOBarnes** [comment]
I would do the following:
- separate out the lines for the hourly triggered step function
- Remove second line from the RDS to the top step function
- Have the ECS fork off to  the RDS, where it is reading from, the dashboard, which it is hosting, then the apis which it is reading from.
- Remove the line connecting the two lambdas

**Comment by MurasatoNaoya** [comment]
But the dashboard when taking in doesn’t use the ECS directly, that’s more Steamlit functionality.

**Comment by MurasatoNaoya** [comment]
On second thought, the dashboard is being hosted using ECS as a task, so any subscriber input data would of course have to be processed by  ECS.  I will change the architecture diagram so both lines from the dashboard run through the ECS icon.

**Comment by AlexOBarnes** [comment]
Thanks for making those changes Andrew, I look forward to reviewing this again
